services:
  authdatabase:
    image: postgres
    container_name: "authDB"
    environment:
      POSTGRES_USER: ${AUTH_USER}
      POSTGRES_PASSWORD: ${AUTH_PASSWORD}
      POSTGRES_DB: ${AUTH_DB}
    ports:
      - 5432:5432
    volumes:
      - data-auth:/var/lib/postgresql/data

volumes:
  data-auth: